name: CI for Linux on Ubuntu

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'build-tools/build-utils.sh'
      - 'build-tools/build-Linux.sh'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  baseSetup:
    uses: ./.github/workflows/Base-Setup.yml
    with:
      host: Linux
      target: linux

  build:
    needs: baseSetup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: false

    - name: Cache vcpkg binary
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg-binary-cache
        key: vcpkg-binary-cache-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

    - name: Build
      env:
        CI_VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        CI_VCPKG_BINARY_SOURCES: "files,${{ github.workspace }}/vcpkg-binary-cache,readwrite"
      run: |
        cd build-tools
        chmod +x build-Linux.sh
        ./build-Linux.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Linux-build
        path: |
          build.Linux/Release/output/
        if-no-files-found: error
